translate russian strings:

    old "Pick"
    new "Выбрать"

    old "Fearless, tough and ruthless, Apes are born warriors and leaders who will do whatever it takes to win. Pledging to the Apes means constantly challenging yourself and fighting your way to the top."
    new "Бесстрашные, жёсткие и безжалостные, Приматы - прирождённые воины и лидеры, которые сделают всё возможное, чтобы победить. Клятва Приматам означает вызов самому себе и борьбу за свой путь к вершине."
    old "Apes"
    new "Приматы"
    old "Honor, loyalty and brotherhood, Wolves bring a touch of chivalry to the world and look out for one another. Pledging to the Wolves means having the determination to be your best self and always having your frat brother’s back."
    new "Честь, верность и братство, Волки приносят в мир нотку рыцарства и заботу друг о друге. Клятва Волкам означает решимость быть самим собой и всегда иметь поддержку своего брата по братству."
    old "Wolves"
    new "Волки"

    old "The Girls of College Kings"
    new "Девушки College Kings"
    old "Click on a girl to change your decisions about her or click continue to start College Kings."
    new "Нажмите на девушку, чтобы изменить своё решение относительно неё, или нажми Продолжить, чтобы начать College Kings."
#    old "Continue"
#    new "Продолжить"
    old "Penelope is in the same history class as me, but the first time we actually spoke was when she randomly stopped me in the street. Straight away I was struck by how quirky she was. Definitely an endearing quality, and I like how she was different to the girls I'd already met."
    new "Пенелопа учится со мной в том же классе истории, но в первый раз мы по-настоящему поговорили, когда она случайно остановила меня на улице. Меня сразу же поразило, насколько она причудлива. Определенно привлекательное качество, и мне нравится, как она отличалась от других девушек, которых я уже встречал."
    old "Pursue relationship"
    new "Стремиться к отношениям"
    old "Be friends"
    new "Быть другом"
    old "Emily, my ex from high school, was starting college too. She wanted to apologize for cheating on me and ruining our relationship."
    new "Эмили, моя бывшая со средней школы, тоже поступали в мой колледж. Она хотела извиниться за то, что изменила мне и разрушила наши отношения."
    old "Forgive her"
    new "Простить её"
    old "Don't forgive her"
    new "Не прощать её"
    old "Autumn is Lauren's older sister, and I got the impression that she was more of a long-term challenge if anything serious was ever going to develop between us. I had opportunities to spend some time with her though to start putting the work in, and to learn more about what makes her tick."
    new "Отэм - старшая сестра Лорен, и у меня сложилось впечатление, что она была скорее долгосрочный вызов, если между нами вообще будет что-то серьезное. У меня была возможность провести некоторое время с ней, хотя бы начать работать, и узнать больше о том, что заставляет ее работать."
    old "Spend time with her"
    new "Проводить с ней время"
    old "Don't spend time with her"
    new "Не проводить с ней время"
    old "Ms Rose is our economics teacher, and later I found out she's also Nora's stepmom! After fully expecting some crusty old professor type to be teaching us economics, I was pleasantly surprised to see her at the front of the class."
    new "Мисс Роуз - наш учитель экономики, а позже я узнал, что она ещё и мачеха Норы! Ожидая, что экономику нам будет преподавать какой-нибудь дряхлый старый профессор, я был приятно удивлён, увидев её в начале семестра."
#    old "Pursue relationship"
#    new "Стремиться к отношениям"
#    old "Be friends"
#    new "Быть другом"
    old "I sat next to Lauren in Economics class on my first day and we hit it off straight away."
    new "В первый день я сидел рядом с Лорен в классе экономики, и мы сразу же нашли общий язык."
#    old "Pursue relationship"
#    new "Стремиться к отношениям"
#    old "Be friends"
#    new "Быть другом"
    old "Like Lauren, Riley has been in my life since my very first day on campus. She always seemed to be the girl making herself available for a chat, and was clearly someone I could dependent on, as well as fun to be around."
    new "Как и Лорен, Райли была в моей жизни с самого первого дня моего пребывания в кампусе. Она всегда казалась девушкой, готовой поболтать, и была человеком, на которого я мог положиться, а также веселым человеком."
#    old "Pursue relationship"
#    new "Стремиться к отношениям"
#    old "Be friends"
#    new "Быть другом"
    old "Nora's been dating Chris, the Wolves president, since before I arrived at college. This didn't stop me being able to flirt with her though. And their relationship didn't seem to be going all that great, so somebody had to give her the attention she was missing."
    new "Нора встречалась с Крисом, президентом Волков, ещё до моего приезда в колледж. Однако это не мешало мне флиртовать с ней. И, похоже, их отношения складывались не лучшим образом, так что кто-то должен был уделять ей внимание, которого ей не хватало."
    old "Flirt with her"
    new "Флиртовать с ней"
    old "Don't flirt with her"
    new "Не флиртовать с ней"
    old "Aubrey was one of the most easy-going girls I'd ever met. There was some clear chemistry and she was the first college girl I had the chance to have sex with. She didn't seem the type to want anything serious any time soon, so it was purely going to be a friends-with-benefits deal if I wanted to go that route."
    new "Обри была одной из самых общительных девушек, которых я когда-либо встречал. Между нами была явная химия, и она была первой девушкой из колледжа, с которой у меня был шанс заняться сексом. Она не была похожа на ту, которая хочет чего-то серьезного в ближайшее время, так что это была чисто дружеская сделка с выгодой, если я хотел пойти этим путем."
    old "Have Sex"
    new "Заниматься сексом"
#    old "Be friends"
#    new "Быть другом"
    old "I was at the Apes' frat house party when I first met Chloe. Clearly, she was one of the hottest girls on campus. But they say the hotter they are, the crazier they are. We were doing some obvious flirting, so I felt I had the chance to find out for myself if there was any truth to that saying."
    new "Я был на вечеринке братства Приматов, когда впервые встретил Хлою. Очевидно, она была одной из самых горячих девушек в кампусе. Но, как говорят, чем горячее, тем безумнее. Мы флиртовали, и я решил, что у меня есть шанс выяснить для себя, есть ли в этой поговорке доля правды."
#    old "Pursue relationship"
#    new "Стремиться к отношениям"
#    old "Be friends"
#    new "Быть другом"
    old "My childhood friend, Josh, introduced me to Amber. Straight away I knew she was a party girl, always looking to have fun and enjoy life to the fullest. She was into drinking and taking drugs, but seemed responsible with it rather than totally out of control."
    new "Мой друг детства, Джош, познакомил меня с Эмбер. Я сразу поняла, что она тусовщица, всегда стремится веселиться и наслаждаться жизнью в полной мере. Любит выпить и принимать наркотики, но она оказалась скорее ответственной, чем полностью неуправляемой."
#    old "Pursue relationship"
#    new "Стремиться к отношениям"
#    old "Be friends"
#    new "Быть другом"
    old "Samantha is Cameron's drug-addicted sister. She already had my sympathy for being related to Cameron, but I needed to decide if I wanted to get closer to her or keep my distance."
    new "Саманта - сестра Кэмерона, страдающая наркотической зависимостью. Она уже завоевала мою симпатию из-за родства с Кэмероном, но мне нужно решить, хочу ли я сблизиться с ней или держать дистанцию."
    old "Keep my distance"
    new "Держать дистанцию"
    old "Get Closer"
    new "Приблизиться"
    old "I'd seen Lindsey around a few times but didn't really get to know her until some guy tried to start a fight with me after class one day. She seemed to appreciate the way I dealt with him and starting showing some genuine interest. It was the night of my first big fight tournament and she wanted me to go over to hers right before the main event."
    new "Я видел Линдси несколько раз, но не знал её по-настоящему, пока однажды после занятий какой-то парень не попытался затеять со мной драку. Похоже, ей понравилось, как я с ним разобрался, и она начала проявлять ко мне неподдельный интерес. Это была ночь моего первого большого бойцовского турнира, и она захотела, чтобы я пришёл к ней прямо перед главным событием."
    old "Go see her"
    new "Сходить к ней."
    old "Don't go see her"
    new "Не ходить к ней."
    old "Penelope tried to enroll Jenny into our college by hacking the system, but she got caught and was in a whole heap of trouble. It was kinda weird how I first met Jenny. She sent me a random text one day asking to meet so we can talk about Penelope. To begin with, I had no idea who this Jenny was, but decided there was nothing to lose by meeting up with her. It's too early to say if there's any potential for romance here."
    new "Пенелопа пыталась зачислить Дженни в наш колледж, взломав систему, но её поймали, и она попала в целую кучу неприятностей. Было довольно странно, как я впервые встретил Дженни. Однажды она прислала мне случайное сообщение с предложением встретиться, чтобы поговорить о Пенелопе. Начнём с того, что я понятия не имел, кто такая эта Дженни, но решил, что ничего не теряю, если встречусь с ней. Пока рано говорить о том, есть ли здесь потенциал для романтики."

#Характеристики

    old "birthday"
    new "день рождения"
    old "eyes"
    new "цвет глаз"
    old "hair"
    new "цвет волос"
    old "star_sign"
    new "знак зодиака"
    old "height"
    new "рост"
    old "measurements"
    new "пропорции"
    old "bra_size"
    new "размер бюстгальтера"
    old "favorite_color"
    new "любимый цвет"
