# Перевёл: serj1983 (post.serj@gmail.com)

translate russian strings:

    old "Aaron"
    new "Аарон"
#    old "Adam"
#    new "Адам"
    old "Amber"
    new "Эмбер"
#    old "Mrs. Anderson"
#    new "Миссис Андерсон"
    old "Aubrey"
    new "Обри"
    old "Autumn"
    new "Отем"
#    old "Benjamin"
#    new "Бенджамин"
    old "Cameron"
    new "Кэмерон"
#    old "Car"
#    new "Автомобиль"
    old "Chris"
    new "Крис"
    old "Chloe"
    new "Хлоя"
    old "Clerk"
    new "Продавец"
#    old "Counselor"
#    new "Советница"
#    old "Courtney"
#    new "Кортни"
#    old "Dr. Ehrmantraut"
#    new "Доктор Эрмантраут"
    old "Elijah"
    new "Элай"
    old "Emily"
    new "Эмили"
#    old "Evelyn"
#    new "Эвелин"
    old "Grayson"
    new "Грэйсон"
    old "Imre"
    new "Имре"
#    old "Jeremy"
#    new "Джереми"
#    old "Josh"
#    new "Джош"
    old "Julia"
    new "Джулия"
#    old "Karen"
#    new "Карен"
#    old "Katy"
#    new "Кэти"
#    old "Kim"
#    new "Ким"
    old "Lauren"
    new "Лорен"
    old "Mr. Lee"
    new "Мистер Ли"
    old "Lindsey"
    new "Линдси"
#    old "Mason"
#    new "Мэйсон"
    old "Nora"
    new "Нора"
    old "Penelope"
    new "Пенелопа"
    old "Riley"
    new "Райли"
    old "Ms. Rose"
    new "Мисс Роуз"
    old "Ryan"
    new "Райн"
#    old "Sam"
#    new "Сэм"
#    old "Sarah"
#    new "Сара"
#    old "Security Guard"
#    new "Охранник"
    old "Tom"
    new "Том"
#    old "Tutorial"
#    new "Обучение"
#    old "Uber Driver"
#    new "Водитель Uber"
    old "Unknown"
    new "Неизвестный"
# 6.0
    old "Finn"
    new "Финн"
#    old "Peter"
#    new "Питер"
#    old "Harry"
#    new "Гарри"
#    old "Marcus"
#    new "Маркус"
#    old "Perry"
#    new "Перри"
    old "Host"
    new "Хозяин"
#    old "Matt"
#    new "Мэтт"
#    old "Lisa"
#    new "Лиза"
#    old "Martin"
#    new "Мартин"
    old "Samantha"
    new "Саманта"
    old "Sebastian"
    new "Себастьян"
    old "Waiter"
    new "Официант"
# 7.0
#    old "Caleb"
#    new "Калеб"
#    old "Class"
#    new "Класс"
#    old "Cooper"
#    new "Купер"
#    old "Jaxon"
#    new "Джексон"
#    old "Kai"
#    new "Кай"
#    old "Nerd"
#    new "Зануда"
#    old "Parker"
#    new "Паркер"
    old "Angelica"
    new "Анжелика"
    old "Elisa"
    new "Элиза"
#    old "Teacher"
#    new "Учитель"
#    old "Wesley"
#    new "Уэсли"
    old "Xavier"
    new "Хавьер"
# 8.0
#    old "Speaker Announcement"
#    new "Объявление спикера"
    old "Dean"
    new "Декан"
#    old "Employee"
#    new "Сотрудник"
#    old "Joe"
#    new "Джо"
# 9.0
#    old "Female voice"
#    new "Женский голос"
# 10.0
    old "Ben"
    new "Бен"
#    old "Rachel"
#    new "Рэйчел"
#    old "Eleanor"
#    new "Элеонора"
#    old "Karen"
#    new "Карен"
#    old "Rebecca"
#    new "Ребекка"
    old "Jenny"
    new "Дженни"
#    old "Jerry"
#    new "Джерри"
#    old "Mr. Rose"
#    new "Мистер Роуз"
# 11.0
#    old "Airport Host"
#    new "Принимающая сторона аэропорта"
#    old "Art Director"
#    new "Художественный руководитель"
#    old "Bank Teller"
#    new "Банковский служащий"
    old "Bartender"
    new "Бармен"
#    old "Candy"
#    new "Кэнди"
#    old "Charli"
#    new "Чарли"
#    old "Sales Rep"
#    new "Торговый представитель"
#    old "Dennis"
#    new "Деннис"
    old "Driver"
    new "Водитель"
#    old "Duncan"
#    new "Дункан"
#    old "Ericka"
#    new "Эрика"
#    old "Foxy"
#    new "Фокси"
#    old "Horse"
#    new "Лошадь"
#    old "Jane"
#    new "Джейн"
#    old "Judge"
#    new "Судья"
#    old "Manager"
#    new "Менеджер"
#    old "Rancher"
#    new "Фермер"
#    old "Susan"
#    new "Сьюзан"
# 12.0
#    old "Barber"
#    new "Парикмахер"
#    old "Bishop"
#    new "Епископ"
#    old "Crazy Lady"
#    new "Сумасшедшая"
#    old "Manager"
#    new "Менеджер"
#    old "French Waitress"
#    new "Французская официантка"
#    old "Greeter"
#    new "Хостес"
#    old "Lady Masseuse"
#    new "Массажистка"
#    old "Male Masseuse"
#    new "Массажист"
    old "Naomi"
    new "Наоми"
#    old "Nurse"
#    new "Медсестра"
#    old "Photographer"
#    new "Фотограф"
#    old "Robber"
#    new "Грабитель"
#    old "Tattoo Artist"
#    new "Мастер татуировок"
# 13.0
#    old "Aryssa"
#    new "Арисса"
#    old "Ashton"
#    new "Эштон"
#    old "Host"
#    new "Хозяин"
#    old "Clipps"
#    new "Клиппс"
#    old "Emmy"
#    new "Эмми"
#    old "Gary"
#    new "Гэри"
#    old "Unknown"
#    new "Неизвестный"
#    old "Kourtney"
#    new "Кортни"
#    old "Luuk"
#    new "Луук"
    old "Polly"
    new "Полли"
#    old "Bartender"
#    new "Бармен"
# 14.0
    old "Bird"
    new "Птица"
    old "Elijah's Mother"
    new "Мать Элайя"
#    old "Emerald"
#    new "Эмеральд"
    old "Gentleman"
    new "Джентельмен"
    old "Lady"
    new "Леди"
#    old "Madame"
#    new "Мадам"
#    old "Night Gambler"
#    new "Напёрсточник"
    old "Rubee"
    new "Руби"
#    old "Satin"
#    new "Сатин"
    old "Trainer"
    new "Тренер"
    old "Wolf Trainer"
    new "Дрессировщик волка"
# 15.0
    old "Male student"
    new "Студент"
    old "Female student"
    new "Студентка"
    old "Oscar's owner"
    new "Хозяин Оскара"
    old "Male Buyer"
    new "Покупатель"
    old "Female Buyer"
    new "Покупательница"
    old "Cashier"
    new "Кассир"
    old "Male Actor"
    new "Актёр"
    old "Female Actor"
    new "Актриса"
    old "Booking Admin"
    new "Администратор по бронированию"
    old "Aubrey's Mom"
    new "Мать Обри"
    old "Aubrey's Dad"
    new "Отец Обри"
    old "Uncle Rick"
    new "Дядюшка Рик"
    old "Wedding Officiant"
    new "Священник"
# 16.0

# 17.0
