# Перевёл: serj1983 (post.serj@gmail.com)

translate russian strings:

    old "THIS MODE PROHIBITS YOU FROM SAVING DURING IMPORTANT CHOICES, MEANING ALL CHOICES ARE FINAL. THIS CAN'T BE DISABLED WITHOUT STARTING A NEW GAME."
    new "ЭТОТ РЕЖИМ ЗАПРЕЩАЕТ вам сохраняться во время важных решений, то есть все решения являются окончательными. его нельзя отключить, не начав новую игру."
    old "ENABLE"
    new "ВКЛЮЧИТЬ"
    old "DISABLE"
    new "ОТКЛЮЧИТЬ"

    old "THE NEXT SCENE HAS NSFW CONTENT"
    new "СЛЕДУЮЩАЯ СЦЕНА ИМЕЕТ СОДЕРЖАНИЕ NSFW"
    old "* CONTENT NOT SUITABLE FOR TWITCH OR YOUTUBE"
    new "* КОНТЕНТ, НЕ ПОДХОДЯЩИЙ ДЛЯ TWITCH ИЛИ YOUTUBE"
    old "TO VIEW THIS SCENE YOU MUST HAVE NSFW ENABLED"
    new "ДЛЯ ПРОСМОТРА ЭТОЙ СЦЕНЫ У ВАС ДОЛЖНО БЫТЬ ВКЛЮЧЕНО NSFW"
    old "IN THE SETTINGS MENU"
    new "В МЕНЮ НАСТРОЕК"
    old "YOU HAVE NSFW CONTENT ENABLED SO YOU MAY"
    new "У ВАС ВКЛЮЧЕН КОНТЕНТ NSFW, ПОЭТОМУ ВЫ МОЖЕТЕ"
    old "CONTINUE TO VIEW THE FOLLOWING SCENE"
    new "ПРОДОЛЖИТЬ ПРОСМОТР СЛЕДУЮЩЕЙ СЦЕНЫ"
    old "OR YOU MAY CHOOSE TO SKIP THIS SCENE"
    new "ИЛИ ВЫ МОЖЕТЕ ПРОПУСТИТЬ ЭТУ СЦЕНУ"
    old "YOU'VE JUST UNLOCKED THE SOCIAL MEDIA APP KIWII! OPEN IT NOW FROM THE HOMESCREEN."
    new "ВЫ ТОЛЬКО ЧТО РАЗБЛОКИРОВАЛИ ПРИЛОЖЕНИЕ ДЛЯ СОЦИАЛЬНЫХ СЕТЕЙ KIWII! ОТКРОЙТЕ ЕГО С ДОМАШНЕГО ЭКРАНА."
    old "CONGRATULATIONS! YOU HAVE LEARNED A NEW FIGHTING MOVE: {{b}}{}{{/b}}."
    new "ПОЗДРАВЛЯЕМ! ВЫ ВЫУЧИЛИ НОВЫЙ БОЕВОЙ ПРИЕМ: {{b}}{}{{/b}}."
    old "WHAT'S NEW:"
    new "ЧТО НОВОГО:"
