# Перевёл: serj1983 (post.serj@gmail.com)
translate russian style tutorial_text:
    font "fonts/OpenSans.ttf"

translate russian strings:
#v1
    old "This is the phone screen. You can access your phone whenever the phone icon in the top right corner appears."
    new "Это экран телефона. Вы можете обращаться к телефону всякий раз, когда в правом верхнем углу появляется значок телефона."
    old "Blue dots show notifications. New notifications are usually accommpanied by a buzz sound. Currently you have a new message waiting for you."
    new "Синие точки показывают уведомления. Новые уведомления обычно сопровождаются звуковым сигналом. В данный момент вас ожидает новое сообщение."
    old "How you reply to messages matters just as much as any other decision."
    new "То, как вы отвечаете на сообщения, имеет такое же значение, как и любое другое решение."
    old "Over the course of the game you will also unlock all kinds of new apps, such as statistics or social media platforms."
    new "В ходе игры вы также разблокируете всевозможные новые приложения, например, статистику или платформы социальных сетей."
    old "Lastly, if you ever need to get to the homescreen, just click the bottom border of the phone, or the phone icon."
    new "Наконец, если вам понадобится перейти на домашний экран, просто нажмите на нижнюю границу телефона или на значок телефона."

    old "Your decisions strongly influence the way the story progresses and how other characters perceive you."
    new "Ваши решения сильно влияют на то, как развивается сюжет и как другие персонажи воспринимают вас."
    old "With each choice you'll either gain Bro, Boyfriend or Troublemaker points."
    new "При каждом выборе вы будете получать очки Брат, Парень или Смутьян."
    old "Bros put the squad first, boyfriends show strong affinity towards a few selected individuals and troublemakers seek thrills and take risks."
    new "Братья ставят команду на первое место, парни проявляют сильную привязанность к нескольким избранным личностям, а нарушители спокойствия ищут острых ощущений и идут на риск."
    old "These points are then used to identify your Key Character Trait (KCT).  Each KCT will unlock different possibilities and choices, but you can only have one active at a time."
    new "Эти очки затем используются для определения вашей ключевой черты характера (KCT). Каждая KCT открывает различные возможности и выбор, но одновременно активной может быть только одна."
    old "You can read more about each individual KCT in the Stats app on your phone."
    new "Вы можете узнать больше о каждом отдельном KCT в приложении статистики на вашем телефоне."

    old "At certain parts of the game, you'll unlock free roam."
    new "На определенных этапах игры вы сможете разблокировать свободное перемещение."
    old "During free roam, you choose where you go and who you want to talk to next."
    new "Во время свободного перемещения вы сами выбираете, куда пойти и с кем поговорить в следующий раз."
    old "You will also be able to use your phone and you might just find some hidden content."
    new "Вы также сможете использовать свой телефон и, возможно, найдете скрытый контент."
#v2
    old "When people make important decisions on how they feel about you, they consider what kind of a person you are."
    new "Когда люди принимают важные решения о том, как они к вам относятся, они учитывают, что вы за человек."
    old "Your Key Character Trait (Loyal, Popular or Confident) has a strong influence on how other characters react to your behavior."
    new "Ваша ключевая черта характера (лояльность, популярность или уверенность) оказывает сильное влияние на то, как другие персонажи реагируют на ваше поведение."
    old "Some people value a popular leader, some care more about loyalty than status and some are drawn to confidence."
    new "Кто-то ценит популярного лидера, кому-то важнее лояльность, чем статус, а кого-то привлекает уверенность в себе."
    old "Your decisions matter and have long time effects, as you can only have one KCT at a time. So think about what kind of person you want to be."
    new "Ваши решения важны и имеют долгосрочные последствия, поскольку одновременно у вас может быть только один KCT. Поэтому подумайте, каким человеком вы хотите стать."

    old "WOULD YOU LIKE TO PLAY THE FIGHTING TUTORIAL?"
    new "Хотите сыграть в обучающий бой?"

    old "ONCE YOU DECIDE WHICH OUTFIT TO BUY, YOU WILL NO LONGER BE ABLE TO PLAY THROUGH ALL OF THE \"TRY\" SCENES. ARE YOU SURE YOU WANT TO CONTINUE?"
    new "Как только вы решите, какой наряд купить, вы больше не сможете пройти все сцены. Вы уверены, что хотите продолжить?"
#v7_screens
    old "I'm not that close with Amber but she does seem quite flirty around me"
    new "Я не настолько близок с Эмбер, но она кажется довольно кокетливой рядом со мной"
    old "Aubrey and I get along well, she might be down to go with me."
    new "Мы с Обри хорошо ладим, возможно, она согласится пойти со мной."
    old "I'm pretty sure that Aubrey would go with me and that would probably lead to a pretty hot night afterwards..."
    new "Я почти уверен, что Обри пошла бы со мной, и это, вероятно, привело бы к довольно жаркой ночи после этого..."
    old "Autumn and I aren't really close, but I'll never know if she'd say yes if I don't try."
    new "Мы с Отэм не очень близки, но я никогда не узнаю, скажет ли она да, если я не попытаюсь."
    old "I think Autumn might be mad at me, so I probably shouldn't ask her."
    new "Я думаю, что Отэм может злиться на меня, так что мне, наверное, не стоит ее спрашивать."
    old "Chloe and I have been getting closer recently. Who knows, I might have a shot."
    new "В последнее время мы с Хлоей становимся все ближе. Кто знает, может быть, у меня есть шанс."
    old "I think Chloe is mad at me, so I probably shouldn't ask her."
    new "Я думаю, Хлоя злится на меня, так что мне, наверное, не стоит ее спрашивать."
    old "I could take Emily. She definitely still has a thing for me."
    new "Я мог бы взять Эмили. Она определенно все еще неравнодушна ко мне."
    old "I don't think asking Emily is the right call."
    new "Я не думаю, что спрашивать Эмили - это правильный выбор."
    old "I'm not sure Lauren sees me as more than a friend, but we have been getting closer."
    new "Я не уверен, что Лорен видит во мне больше, чем друга, но мы становимся ближе."
    old "It's kinda weird between Lauren and me, I probably should ask someone else."
    new "Это как-то странно между мной и Лорен, наверное, мне стоит спросить кого-нибудь другого."
    old "Penelope didn't seem too eager to talk to me today, I better ask someone else."
    new "Пенелопа, похоже, не слишком горела желанием разговаривать со мной сегодня, мне лучше спросить кого-нибудь другого."
    old "Penelope and I got along really well when we went bowling together, I think she could say yes."
    new "Мы с Пенелопой очень хорошо ладили, когда вместе ходили в боулинг, я думаю, она могла бы сказать да."
    old "I haven't done that much with Penelope so far, but maybe she'll yes."
    new "До сих пор я не так много делал с Пенелопой, но, возможно, она согласится."
    old "Riley and I are good friends. She might say yes if I ask her."
    new "Мы с Райли хорошие друзья. Она может сказать да, если я её попрошу."
    old "Lauren would kill me if I asked someone other than her."
    new "Лорен убьет меня, если я спрошу кого-нибудь, кроме неё."
    old "I could always go alone..."
    new "Я всегда мог бы пойти один..."
    old "ARE YOU SURE YOU WANT TO END THE FREE ROAM WITH CHLOE?"
    new "Ты уверен, что хочешь закончить свободное перемещение с Хлоей?"
    old "ARE YOU SURE YOU WANT TO END THE FREE ROAM WITH EMILY?"
    new "Ты уверен, что хочешь закончить свободное перемещение с Эмили?"
    old "ARE YOU SURE YOU WANT TO END THE FREE ROAM WITH LAUREN?"
    new "Ты уверен, что хочешь закончить свободное перемещение с Лорен?"
    old "ARE YOU SURE YOU WANT TO END THE FREE ROAM WITH PENELOPE?"
    new "Ты уверен, что хочешь закончить свободное перемещение с Пенелопой?"
    old "ARE YOU SURE YOU WANT TO END THE FREE ROAM WITH RILEY?"
    new "Ты уверен, что хочешь закончить свободное перемещение с Райли?"
    old "THIS ACT HAS VOICE ACTED SEX SCENES. EACH GIRL HAS A UNIQUE VOICE AND MOANS ACCORDINGLY. WOULD YOU LIKE TO ENABLE VOICE ACTING IN THE SEX SCENES?"
    new "В этом акте есть озвученные сексуальные сцены. Каждая девушка обладает уникальным голосом и соответственно стонет. Хотели бы вы включить озвучку в сексуальных сценах?"
